#! /usr/bin/env bash
source bin/setup-environment
if [ -n "${TEMPLATE_REPO_URL}" ]; then
  TEMPLATE_ORIGIN_URL=${TEMPLATE_REPO_URL}
else
  MY_ORIGIN_URL=`git config -l | grep remote.origin.url | sed -e s[remote.origin.url=[[g`
  REPO_NAME=`basename ${MY_ORIGIN_URL}`
  ORIGIN_ROOT=${MY_ORIGIN_URL%/${REPO_NAME}}
  TEMPLATES_REPO_NAME=${REPO_NAME/.git/-templates.git}
  TEMPLATE_ORIGIN_URL=${ORIGIN_ROOT}/${TEMPLATES_REPO_NAME}
fi
if [ -d templates ]; then
  rm -rf ./templates
fi
git clone ${TEMPLATE_ORIGIN_URL} templates
npm install --production .
